server:
  port: 8085
  servlet:
    context-path: /puppy
spring:

#  datasource:
#   driverClassName: com.mysql.cj.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/puppylink?serverTimezone=Asia/Seoul
#   username: puppy
#   password: ssafy

  jpa:
    open-in-view: true
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: puppylink1114@gmail.com
    password: kecakievjnmannnd
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          timeout: 5000
          starttls:
            enable: true
            required: true
#  session:
#    store-type: redis
#  redis:
#    host: localhost
#    port: 6379
  cache:
    type: redis


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
  profiles:
    active: dev   #application-dev.yml을 부름

logging:
  level:
    web: INFO
    root: INFO
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
